### PR TITLE
migrate to TS + Functional

### PR DESCRIPTION
**Pull request by vzsky**

### CODE REVIEW

**Comment by vzsky** [comment]
Typescript helps spotting errors, ensure that the code run smoothly. Functional code and hooks are also easier to write and understand.

**Comment by itzmeowww** [comment]
> Typescript helps spotting errors, ensure that the code run smoothly. Functional code and hooks are also easier to write and understand.

I think there is a conflict.

**Comment by itzmeowww** [comment]
Everything is fine for now

**Comment by vzsky** [comment]
Closed ?

**Comment by itzmeowww** [comment]
> Closed ?

Idk what i'm doing right now 🤯

**Pull request closed without merging**
